default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hearthstone-api-cc_development

test:
  <<: *default
  database: hearthstone-api-cc

production:
  <<: *default
  database: hearthstone-api-cc_production
  username: hearthstone-api-cc
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>